const translationsDetails = {
    "Pereti D - Simplu Placat": 'create_offer_walls_d_simple',
	"Pereti D - Dublu Placat": 'create_offer_walls_d_double',
	"Pereti D - Triplu Placat": 'create_offer_walls_d_triple',
	"Pereti S - Dublu Placat": 'create_offer_walls_s_double',
	"Pereti S - Triplu Placat": 'create_offer_walls_s_triple',
	"Pereti S - Asimetrici": 'create_offer_walls_s_asimetric',
	"Pereti Smart - Simplu Placat": "create_offer_walls_smart_simple",
	"Pereti Smart - Dublu Placat": "create_offer_walls_smart_double",
	"Pereti S - Dublu Intermediar": 'create_offer_walls_s_double_intermediate',
	"Pereti S - Triplu Intermediar": 'create_offer_walls_s_triple_intermediate',
	"Pereti SL - Simplu Placat": 'create_offer_walls_sl_simple',
	"Pereti SL - Dublu Placat": 'create_offer_walls_sl_double',
	"Pereti SL - Triplu Placat": 'create_offer_walls_sl_triple',
	"Pereti SLA - Triplu Placat": 'create_offer_walls_sla_triple',
	"Placari cu fixari - Simple": 'create_offer_plating_fix_simple',
	"Placari cu fixari - Duble": 'create_offer_plating_fix_double',
	"Placari cu fixari - Triple": 'create_offer_plating_fix_triple',
	"Placari cu fixari - Cvadruple": 'create_offer_plating_fix_quadruple',
    "Placari independente - Simple": 'create_offer_plating_indep_simple',
	"Placari independente - Duble": 'create_offer_plating_indep_double',
	"Placari independente - Triple": 'create_offer_plating_indep_triple',
	"Placari independente - Cvadruple": 'create_offer_plating_indep_quadruple',
    "Placari liniare - Duble": 'create_offer_plating_liniar_double',
	"Placari liniare - Triple": 'create_offer_plating_liniar_triple',
	"Placari liniare - Cvadruple": 'create_offer_plating_liniar_quadruple',
	"Placari Lipire": 'create_offer_plating_sticking',
    "Placari Noisy cu fixari - Triple": 'create_offer_noisy_plating_fix_triple',
    "Placari Noisy independente - Duble": 'create_offer_noisy_plating_indep_double',
    "Placari Noisy independente - Triple": 'create_offer_noisy_plating_indep_triple',
    "Placari Noisy UU - Duble": 'create_offer_noisy_plating_uu_double',
    "Placari Noisy UU - Triple": 'create_offer_noisy_plating_uu_triple',
	"Plafoane Suspendate - Simple": 'create_offer_ceiling_suspended_simple',
	"Plafoane Suspendate - Duble": 'create_offer_ceiling_suspended_double',
	"Plafoane Suspendate - Triple": 'create_offer_ceiling_suspended_triple',
	"Plafoane Suspendate - Cvadruple": 'create_offer_ceiling_suspended_quadruple',
	"Plafoane Autoportante - Simple": 'create_offer_ceiling_autoport_simple',
	"Plafoane Autoportante - Duble": 'create_offer_ceiling_autoport_double',
	"Plafoane Autoportante - Triple": 'create_offer_ceiling_autoport_triple',
	"Plafoane Autoportante - Cvadruple": 'create_offer_ceiling_autoport_quadruple',
	"fata": "moisture_face",
	"fara": 'interax_spacing',
	"Brosura pereti": "brochures_walls",
	"Brosura placari": "brochures_platings",
	"Brosura plafoane": "brochures_ceilings",
}

module.exports = translationsDetails

