const mongoose = require('mongoose');

const offerSchema = new mongoose.Schema({
    createdAt: mongoose.Schema.Types.Date,
    savedOfferId: mongoose.Schema.Types.ObjectId, 
    userId: mongoose.Schema.Types.ObjectId, 
    status: mongoose.Schema.Types.String,
    excelName: mongoose.Schema.Types.String,
    surface: mongoose.Schema.Types.Number,
    distance: mongoose.Schema.Types.Number,
    thickness: mongoose.Schema.Types.Number,
    soundInsulationMin: mongoose.Schema.Types.Number,
    soundInsulationMax: mongoose.Schema.Types.Number,
    basedPlates: mongoose.Schema.Types.String,
    intermediatePlate: mongoose.Schema.Types.String,
    thicknessSystem: mongoose.Schema.Types.String,
    protectionSense: mongoose.Schema.Types.String,
    profileType: mongoose.Schema.Types.String,
    height: mongoose.Schema.Types.Number,
    fireResistance: mongoose.Schema.Types.String,
    interax: mongoose.Schema.Types.String,
    moistureResistance: mongoose.Schema.Types.String,
    burglaryResistance: mongoose.Schema.Types.String,
    interaxSustineri: mongoose.Schema.Types.String,
    soundInsulation: mongoose.Schema.Types.String,
    support: mongoose.Schema.Types.String,
    structureLink: mongoose.Schema.Types.String,
    ceilingSupport: mongoose.Schema.Types.String,
    finishing: mongoose.Schema.Types.String,
    izolareAcustica: mongoose.Schema.Types.Number,
    systemCode: mongoose.Schema.Types.String,
    systemCodeTable: mongoose.Schema.Types.String,
    codSap1: mongoose.Schema.Types.String,
    codSap2: mongoose.Schema.Types.String,
    codSap3: mongoose.Schema.Types.String,
    systemName: mongoose.Schema.Types.String,
    plate: {
        face1: {
            plate1: mongoose.Schema.Types.String,
            plate2: mongoose.Schema.Types.String,
            plate3: mongoose.Schema.Types.String,
        },
        face2: {
            plate1: mongoose.Schema.Types.String,
            plate2: mongoose.Schema.Types.String,
            plate3: mongoose.Schema.Types.String,
            plate4: mongoose.Schema.Types.String,
        },
    },
    initialPlate: {
        face1: {
            plate1: mongoose.Schema.Types.String,
            plate2: mongoose.Schema.Types.String,
            plate3: mongoose.Schema.Types.String,
        },
        face2: {
            plate1: mongoose.Schema.Types.String,
            plate2: mongoose.Schema.Types.String,
            plate3: mongoose.Schema.Types.String,
            plate4: mongoose.Schema.Types.String,
        },
    },
    platingPlates: {
        plate1: mongoose.Schema.Types.String,
        plate2: mongoose.Schema.Types.String,
        plate3: mongoose.Schema.Types.String,
        plate4: mongoose.Schema.Types.String,
    },
    platingInitialPlates: {
        plate1: mongoose.Schema.Types.String,
        plate2: mongoose.Schema.Types.String,
        plate3: mongoose.Schema.Types.String,
        plate4: mongoose.Schema.Types.String,
    },
    price: mongoose.Schema.Types.Number,
    consumption: mongoose.Schema.Types.Array,
    consumptionExterior: mongoose.Schema.Types.Array,
});

module.exports = offerSchema;